### ISSUE TITLE
Change the way citation information is displayed

### ISSUE THREAD

**Issue by marianneb** [jcu-eresearch/TDH-Research-Data-Catalogue#11]
The citation content for non-privileged users (e.g. guest or researcher) should show the  citation string send to RDA (see rif.vm) instead of individual metadata fields. I would also like a download citation in EndNote or BibTex format feature added here as well.

**Comment by ozej8y** [comment]
The citation string has been added under issue #17.

**Comment by ozej8y** [comment]
This issue has passed testing and has been deployed to production.
