### ISSUE TITLE
Change display of citation information in the detail view

### ISSUE THREAD

**Issue by marianneb** [jcu-eresearch/TDH-Research-Data-Catalogue#13]
I would like the citation string ( as it is sent to RDA ) to be displayed on the detail view instead of the individual metadata fields. It would be great is we could make the citation data available for download in EndNote format but that might be asking a bit much :)

**Comment by ozej8y** [comment]
Citation string has been added under issue #17. EndNote functionality under investigation.

**Comment by ozej8y** [comment]
Added a separate issue for the EndNote functionality.

**Comment by ozej8y** [comment]
This issue has passed testing and has been deployed to production.
