### ISSUE TITLE
Display DOI on the citation tab.

### ISSUE THREAD

**Issue by ozej8y** [jcu-eresearch/TDH-Research-Data-Catalogue#17]
Now that DOI's have been turned on, provide the outside user with a field to see their DOI.

**Comment by ozej8y** [comment]
The DOI is now displayed under Citation for public view.

I have altered the Citation tab so that it now only displays the Citation string, not all the other fields. The citation string is using the same logic as that for the RIF-CS.

After looking at a few citations in Research Data and RDA, I think the logic may need some tweaking.
e.g. McComiskie, R. (2014). State of the Tropics - Society - Health - Under 5 mortality. James Cook University. [Data files] 50b06e76d6427812e4cda41b01613d99

I would expect the ID to be more meaningful. e.g. a URL like most of the other records.

**Comment by ozej8y** [comment]
Awaiting deployment to eResearch.

**Comment by RobDonaldson** [comment]
Hey guys,

I hope all has been well, just a heads up that it appears I am still
attached to the github repo haha,

Thanks

Rob.

**Comment by LaurenHodgson** [comment]
Me too, haha. It's nostalgic

**Comment by afakes** [comment]
And me Adam fakes

**Comment by ozej8y** [comment]
Hi Rob, Lauren and Adam,

How are you all going ?

You are all following this repo. Maybe you can unfollow.
I don’t seem to be able to do this for you.

I looked at the research repo at a higher level and it looks like your admin access has been removed.

Cheers,
             Jay.

**Comment by ozej8y** [comment]
This issue has passed testing and has been deployed to production.
