### ISSUE TITLE
Attachments (self submission) not visible to non-logged in users

### ISSUE THREAD

**Issue by marianneb** [jcu-eresearch/TDH-Research-Data-Catalogue#21]
Attached data files from self-submissions are not appearing on in the "Data" tab of the details view. The Velocity template does some checking to see if files are public or private before displaying and looks like attachments from self-submissions are being prevented from display.

**Comment by ozej8y** [comment]
A fix to prevent this issue has been implemented in attachment-file-rules.py.
Fixing existing attachments is a problem. The file is kept in the 'storage' folder.
A script is being developed to replace this file with the new one.
e.g.
1. tar up the storage folder.
2. deploy updated redbox.
3. untar storage.
4. run a script to replace attachment-file-rules.py with the new versions.
5. run tf_restore.sh. 

This should fix it. Currently investigating and testing.

**Comment by ozej8y** [comment]
This issue has passed testing and has been deployed to production.
